valor = input('Digite algo: ')
prim = type(valor)

print('O tip primitivo de {} é {}'.format(valor, prim))
print('Esse valor é alfanumérico?', valor.isalnum())
print('Esse valor é alfabético?', valor.isalpha())
print('Esse valor é numérico?', valor.isnumeric())
print('Esse valor é decimal?', valor.isdecimal())
print('Esse valor é um espaço?', valor.isspace())
print('Esse valor está todo em minúsculo?', valor.islower())
print('Esse valor esta todo em maiúsculo?', valor.isupper())
print('Esse valor está capitalizada?', valor.istitle())
print('Esse valor é identificador válido?', valor.isidentifier())
print('Esse valor é imprimivel?', valor.isprintable())
print('Esse valor é ascii?', valor.isascii())
print('Esse valor é digito?', valor.isdigit())
